import db from './db';
import { createTables } from './schema';

/**
 * Dados das 20 seleções da Copa do Mundo 2022 com 20 jogadores reais cada.
 * Total: 400 figurinhas.
 */
interface PlayerSeed {
  name: string;
  position: string;
}

interface TeamSeed {
  country: string;
  players: PlayerSeed[];
}

const teams: TeamSeed[] = [
  {
    country: 'Brasil',
    players: [
      { name: 'Alisson', position: 'Goleiro' },
      { name: 'Ederson', position: 'Goleiro' },
      { name: 'Thiago Silva', position: 'Defensor' },
      { name: 'Marquinhos', position: 'Defensor' },
      { name: 'Militão', position: 'Defensor' },
      { name: 'Danilo', position: 'Defensor' },
      { name: 'Alex Sandro', position: 'Defensor' },
      { name: 'Bremer', position: 'Defensor' },
      { name: 'Casemiro', position: 'Meio-campista' },
      { name: 'Lucas Paquetá', position: 'Meio-campista' },
      { name: 'Fred', position: 'Meio-campista' },
      { name: 'Fabinho', position: 'Meio-campista' },
      { name: 'Bruno Guimarães', position: 'Meio-campista' },
      { name: 'Éverton Ribeiro', position: 'Meio-campista' },
      { name: 'Neymar', position: 'Atacante' },
      { name: 'Vinícius Jr.', position: 'Atacante' },
      { name: 'Richarlison', position: 'Atacante' },
      { name: 'Raphinha', position: 'Atacante' },
      { name: 'Rodrygo', position: 'Atacante' },
      { name: 'Antony', position: 'Atacante' },
    ],
  },
  {
    country: 'Argentina',
    players: [
      { name: 'Emiliano Martínez', position: 'Goleiro' },
      { name: 'Franco Armani', position: 'Goleiro' },
      { name: 'Nicolás Otamendi', position: 'Defensor' },
      { name: 'Cristian Romero', position: 'Defensor' },
      { name: 'Lisandro Martínez', position: 'Defensor' },
      { name: 'Nahuel Molina', position: 'Defensor' },
      { name: 'Nicolás Tagliafico', position: 'Defensor' },
      { name: 'Marcos Acuña', position: 'Defensor' },
      { name: 'Rodrigo De Paul', position: 'Meio-campista' },
      { name: 'Enzo Fernández', position: 'Meio-campista' },
      { name: 'Leandro Paredes', position: 'Meio-campista' },
      { name: 'Alexis Mac Allister', position: 'Meio-campista' },
      { name: 'Guido Rodríguez', position: 'Meio-campista' },
      { name: 'Exequiel Palacios', position: 'Meio-campista' },
      { name: 'Lionel Messi', position: 'Atacante' },
      { name: 'Ángel Di María', position: 'Atacante' },
      { name: 'Julián Álvarez', position: 'Atacante' },
      { name: 'Lautaro Martínez', position: 'Atacante' },
      { name: 'Paulo Dybala', position: 'Atacante' },
      { name: 'Nicolás González', position: 'Atacante' },
    ],
  },
  {
    country: 'França',
    players: [
      { name: 'Hugo Lloris', position: 'Goleiro' },
      { name: 'Steve Mandanda', position: 'Goleiro' },
      { name: 'Raphaël Varane', position: 'Defensor' },
      { name: 'Dayot Upamecano', position: 'Defensor' },
      { name: 'Jules Koundé', position: 'Defensor' },
      { name: 'Theo Hernández', position: 'Defensor' },
      { name: 'Benjamin Pavard', position: 'Defensor' },
      { name: 'Ibrahima Konaté', position: 'Defensor' },
      { name: 'Aurélien Tchouaméni', position: 'Meio-campista' },
      { name: 'Adrien Rabiot', position: 'Meio-campista' },
      { name: 'Youssouf Fofana', position: 'Meio-campista' },
      { name: 'Eduardo Camavinga', position: 'Meio-campista' },
      { name: 'Jordan Veretout', position: 'Meio-campista' },
      { name: 'Mattéo Guendouzi', position: 'Meio-campista' },
      { name: 'Kylian Mbappé', position: 'Atacante' },
      { name: 'Antoine Griezmann', position: 'Atacante' },
      { name: 'Olivier Giroud', position: 'Atacante' },
      { name: 'Ousmane Dembélé', position: 'Atacante' },
      { name: 'Kingsley Coman', position: 'Atacante' },
      { name: 'Marcus Thuram', position: 'Atacante' },
    ],
  },
  {
    country: 'Alemanha',
    players: [
      { name: 'Manuel Neuer', position: 'Goleiro' },
      { name: 'Marc-André ter Stegen', position: 'Goleiro' },
      { name: 'Antonio Rüdiger', position: 'Defensor' },
      { name: 'Niklas Süle', position: 'Defensor' },
      { name: 'Nico Schlotterbeck', position: 'Defensor' },
      { name: 'David Raum', position: 'Defensor' },
      { name: 'Thilo Kehrer', position: 'Defensor' },
      { name: 'Lukas Klostermann', position: 'Defensor' },
      { name: 'Joshua Kimmich', position: 'Meio-campista' },
      { name: 'İlkay Gündoğan', position: 'Meio-campista' },
      { name: 'Leon Goretzka', position: 'Meio-campista' },
      { name: 'Jamal Musiala', position: 'Meio-campista' },
      { name: 'Kai Havertz', position: 'Meio-campista' },
      { name: 'Jonas Hofmann', position: 'Meio-campista' },
      { name: 'Thomas Müller', position: 'Atacante' },
      { name: 'Serge Gnabry', position: 'Atacante' },
      { name: 'Leroy Sané', position: 'Atacante' },
      { name: 'Niclas Füllkrug', position: 'Atacante' },
      { name: 'Youssoufa Moukoko', position: 'Atacante' },
      { name: 'Karim Adeyemi', position: 'Atacante' },
    ],
  },
  {
    country: 'Espanha',
    players: [
      { name: 'Unai Simón', position: 'Goleiro' },
      { name: 'Robert Sánchez', position: 'Goleiro' },
      { name: 'Dani Carvajal', position: 'Defensor' },
      { name: 'Aymeric Laporte', position: 'Defensor' },
      { name: 'Pau Torres', position: 'Defensor' },
      { name: 'Jordi Alba', position: 'Defensor' },
      { name: 'César Azpilicueta', position: 'Defensor' },
      { name: 'Eric García', position: 'Defensor' },
      { name: 'Sergio Busquets', position: 'Meio-campista' },
      { name: 'Pedri', position: 'Meio-campista' },
      { name: 'Gavi', position: 'Meio-campista' },
      { name: 'Koke', position: 'Meio-campista' },
      { name: 'Carlos Soler', position: 'Meio-campista' },
      { name: 'Marcos Llorente', position: 'Meio-campista' },
      { name: 'Álvaro Morata', position: 'Atacante' },
      { name: 'Ferran Torres', position: 'Atacante' },
      { name: 'Marco Asensio', position: 'Atacante' },
      { name: 'Dani Olmo', position: 'Atacante' },
      { name: 'Ansu Fati', position: 'Atacante' },
      { name: 'Nico Williams', position: 'Atacante' },
    ],
  },
  {
    country: 'Portugal',
    players: [
      { name: 'Diogo Costa', position: 'Goleiro' },
      { name: 'Rui Patrício', position: 'Goleiro' },
      { name: 'Pepe', position: 'Defensor' },
      { name: 'Rúben Dias', position: 'Defensor' },
      { name: 'João Cancelo', position: 'Defensor' },
      { name: 'Nuno Mendes', position: 'Defensor' },
      { name: 'Danilo Pereira', position: 'Defensor' },
      { name: 'Raphaël Guerreiro', position: 'Defensor' },
      { name: 'Bernardo Silva', position: 'Meio-campista' },
      { name: 'Bruno Fernandes', position: 'Meio-campista' },
      { name: 'Vitinha', position: 'Meio-campista' },
      { name: 'William Carvalho', position: 'Meio-campista' },
      { name: 'Rúben Neves', position: 'Meio-campista' },
      { name: 'Otávio', position: 'Meio-campista' },
      { name: 'Cristiano Ronaldo', position: 'Atacante' },
      { name: 'João Félix', position: 'Atacante' },
      { name: 'Rafael Leão', position: 'Atacante' },
      { name: 'Gonçalo Ramos', position: 'Atacante' },
      { name: 'Ricardo Horta', position: 'Atacante' },
      { name: 'André Silva', position: 'Atacante' },
    ],
  },
  {
    country: 'Inglaterra',
    players: [
      { name: 'Jordan Pickford', position: 'Goleiro' },
      { name: 'Aaron Ramsdale', position: 'Goleiro' },
      { name: 'Harry Maguire', position: 'Defensor' },
      { name: 'John Stones', position: 'Defensor' },
      { name: 'Kyle Walker', position: 'Defensor' },
      { name: 'Luke Shaw', position: 'Defensor' },
      { name: 'Kieran Trippier', position: 'Defensor' },
      { name: 'Eric Dier', position: 'Defensor' },
      { name: 'Declan Rice', position: 'Meio-campista' },
      { name: 'Jude Bellingham', position: 'Meio-campista' },
      { name: 'Mason Mount', position: 'Meio-campista' },
      { name: 'Jordan Henderson', position: 'Meio-campista' },
      { name: 'Kalvin Phillips', position: 'Meio-campista' },
      { name: 'Conor Gallagher', position: 'Meio-campista' },
      { name: 'Harry Kane', position: 'Atacante' },
      { name: 'Raheem Sterling', position: 'Atacante' },
      { name: 'Bukayo Saka', position: 'Atacante' },
      { name: 'Phil Foden', position: 'Atacante' },
      { name: 'Marcus Rashford', position: 'Atacante' },
      { name: 'Jack Grealish', position: 'Atacante' },
    ],
  },
  {
    country: 'Holanda',
    players: [
      { name: 'Andries Noppert', position: 'Goleiro' },
      { name: 'Remko Pasveer', position: 'Goleiro' },
      { name: 'Virgil van Dijk', position: 'Defensor' },
      { name: 'Nathan Aké', position: 'Defensor' },
      { name: 'Jurriën Timber', position: 'Defensor' },
      { name: 'Daley Blind', position: 'Defensor' },
      { name: 'Denzel Dumfries', position: 'Defensor' },
      { name: 'Stefan de Vrij', position: 'Defensor' },
      { name: 'Frenkie de Jong', position: 'Meio-campista' },
      { name: 'Marten de Roon', position: 'Meio-campista' },
      { name: 'Teun Koopmeiners', position: 'Meio-campista' },
      { name: 'Davy Klaassen', position: 'Meio-campista' },
      { name: 'Cody Gakpo', position: 'Meio-campista' },
      { name: 'Xavi Simons', position: 'Meio-campista' },
      { name: 'Memphis Depay', position: 'Atacante' },
      { name: 'Steven Bergwijn', position: 'Atacante' },
      { name: 'Wout Weghorst', position: 'Atacante' },
      { name: 'Vincent Janssen', position: 'Atacante' },
      { name: 'Donyell Malen', position: 'Atacante' },
      { name: 'Noa Lang', position: 'Atacante' },
    ],
  },
  {
    country: 'Bélgica',
    players: [
      { name: 'Thibaut Courtois', position: 'Goleiro' },
      { name: 'Simon Mignolet', position: 'Goleiro' },
      { name: 'Jan Vertonghen', position: 'Defensor' },
      { name: 'Toby Alderweireld', position: 'Defensor' },
      { name: 'Timothy Castagne', position: 'Defensor' },
      { name: 'Arthur Theate', position: 'Defensor' },
      { name: 'Leander Dendoncker', position: 'Defensor' },
      { name: 'Thomas Meunier', position: 'Defensor' },
      { name: 'Kevin De Bruyne', position: 'Meio-campista' },
      { name: 'Axel Witsel', position: 'Meio-campista' },
      { name: 'Youri Tielemans', position: 'Meio-campista' },
      { name: 'Amadou Onana', position: 'Meio-campista' },
      { name: 'Hans Vanaken', position: 'Meio-campista' },
      { name: 'Thorgan Hazard', position: 'Meio-campista' },
      { name: 'Eden Hazard', position: 'Atacante' },
      { name: 'Romelu Lukaku', position: 'Atacante' },
      { name: 'Dries Mertens', position: 'Atacante' },
      { name: 'Michy Batshuayi', position: 'Atacante' },
      { name: 'Yannick Carrasco', position: 'Atacante' },
      { name: 'Loïs Openda', position: 'Atacante' },
    ],
  },
  {
    country: 'Croácia',
    players: [
      { name: 'Dominik Livaković', position: 'Goleiro' },
      { name: 'Ivica Ivušić', position: 'Goleiro' },
      { name: 'Dejan Lovren', position: 'Defensor' },
      { name: 'Joško Gvardiol', position: 'Defensor' },
      { name: 'Domagoj Vida', position: 'Defensor' },
      { name: 'Borna Sosa', position: 'Defensor' },
      { name: 'Josip Juranović', position: 'Defensor' },
      { name: 'Josip Stanišić', position: 'Defensor' },
      { name: 'Luka Modrić', position: 'Meio-campista' },
      { name: 'Mateo Kovačić', position: 'Meio-campista' },
      { name: 'Marcelo Brozović', position: 'Meio-campista' },
      { name: 'Mario Pašalić', position: 'Meio-campista' },
      { name: 'Nikola Vlašić', position: 'Meio-campista' },
      { name: 'Lovro Majer', position: 'Meio-campista' },
      { name: 'Ivan Perišić', position: 'Atacante' },
      { name: 'Andrej Kramarić', position: 'Atacante' },
      { name: 'Bruno Petković', position: 'Atacante' },
      { name: 'Marko Livaja', position: 'Atacante' },
      { name: 'Ante Budimir', position: 'Atacante' },
      { name: 'Mislav Oršić', position: 'Atacante' },
    ],
  },
  {
    country: 'Marrocos',
    players: [
      { name: 'Yassine Bounou', position: 'Goleiro' },
      { name: 'Munir Mohamedi', position: 'Goleiro' },
      { name: 'Achraf Hakimi', position: 'Defensor' },
      { name: 'Nayef Aguerd', position: 'Defensor' },
      { name: 'Romain Saïss', position: 'Defensor' },
      { name: 'Noussair Mazraoui', position: 'Defensor' },
      { name: 'Jawad El Yamiq', position: 'Defensor' },
      { name: 'Badr Benoun', position: 'Defensor' },
      { name: 'Sofyan Amrabat', position: 'Meio-campista' },
      { name: 'Azzedine Ounahi', position: 'Meio-campista' },
      { name: 'Selim Amallah', position: 'Meio-campista' },
      { name: 'Bilal El Khannouss', position: 'Meio-campista' },
      { name: 'Abdelhamid Sabiri', position: 'Meio-campista' },
      { name: 'Yahya Jabrane', position: 'Meio-campista' },
      { name: 'Hakim Ziyech', position: 'Atacante' },
      { name: 'Youssef En-Nesyri', position: 'Atacante' },
      { name: 'Sofiane Boufal', position: 'Atacante' },
      { name: 'Abde Ezzalzouli', position: 'Atacante' },
      { name: 'Zakaria Aboukhlal', position: 'Atacante' },
      { name: 'Walid Cheddira', position: 'Atacante' },
    ],
  },
  {
    country: 'Japão',
    players: [
      { name: 'Shūichi Gonda', position: 'Goleiro' },
      { name: 'Daniel Schmidt', position: 'Goleiro' },
      { name: 'Maya Yoshida', position: 'Defensor' },
      { name: 'Yuto Nagatomo', position: 'Defensor' },
      { name: 'Hiroki Sakai', position: 'Defensor' },
      { name: 'Ko Itakura', position: 'Defensor' },
      { name: 'Shogo Taniguchi', position: 'Defensor' },
      { name: 'Takehiro Tomiyasu', position: 'Defensor' },
      { name: 'Wataru Endo', position: 'Meio-campista' },
      { name: 'Gaku Shibasaki', position: 'Meio-campista' },
      { name: 'Hidemasa Morita', position: 'Meio-campista' },
      { name: 'Ao Tanaka', position: 'Meio-campista' },
      { name: 'Ritsu Doan', position: 'Meio-campista' },
      { name: 'Junya Ito', position: 'Meio-campista' },
      { name: 'Takumi Minamino', position: 'Atacante' },
      { name: 'Daichi Kamada', position: 'Atacante' },
      { name: 'Kaoru Mitoma', position: 'Atacante' },
      { name: 'Takuma Asano', position: 'Atacante' },
      { name: 'Ayase Ueda', position: 'Atacante' },
      { name: 'Daizen Maeda', position: 'Atacante' },
    ],
  },
  {
    country: 'Coreia do Sul',
    players: [
      { name: 'Kim Seung-gyu', position: 'Goleiro' },
      { name: 'Jo Hyeon-woo', position: 'Goleiro' },
      { name: 'Kim Min-jae', position: 'Defensor' },
      { name: 'Kim Young-gwon', position: 'Defensor' },
      { name: 'Kim Jin-su', position: 'Defensor' },
      { name: 'Yoon Jong-gyu', position: 'Defensor' },
      { name: 'Cho Yu-min', position: 'Defensor' },
      { name: 'Kim Moon-hwan', position: 'Defensor' },
      { name: 'Son Heung-min', position: 'Atacante' },
      { name: 'Hwang Hee-chan', position: 'Atacante' },
      { name: 'Lee Kang-in', position: 'Meio-campista' },
      { name: 'Jung Woo-young', position: 'Meio-campista' },
      { name: 'Hwang In-beom', position: 'Meio-campista' },
      { name: 'Lee Jae-sung', position: 'Meio-campista' },
      { name: 'Paik Seung-ho', position: 'Meio-campista' },
      { name: 'Kwon Chang-hoon', position: 'Meio-campista' },
      { name: 'Na Sang-ho', position: 'Atacante' },
      { name: 'Cho Gue-sung', position: 'Atacante' },
      { name: 'Song Min-kyu', position: 'Atacante' },
      { name: 'Jeong Woo-yeong', position: 'Atacante' },
    ],
  },
  {
    country: 'EUA',
    players: [
      { name: 'Matt Turner', position: 'Goleiro' },
      { name: 'Ethan Horvath', position: 'Goleiro' },
      { name: 'Sergiño Dest', position: 'Defensor' },
      { name: 'Walker Zimmerman', position: 'Defensor' },
      { name: 'Tim Ream', position: 'Defensor' },
      { name: 'Antonee Robinson', position: 'Defensor' },
      { name: 'Cameron Carter-Vickers', position: 'Defensor' },
      { name: 'DeAndre Yedlin', position: 'Defensor' },
      { name: 'Tyler Adams', position: 'Meio-campista' },
      { name: 'Weston McKennie', position: 'Meio-campista' },
      { name: 'Yunus Musah', position: 'Meio-campista' },
      { name: 'Kellyn Acosta', position: 'Meio-campista' },
      { name: 'Luca de la Torre', position: 'Meio-campista' },
      { name: 'Cristian Roldán', position: 'Meio-campista' },
      { name: 'Christian Pulisic', position: 'Atacante' },
      { name: 'Timothy Weah', position: 'Atacante' },
      { name: 'Brenden Aaronson', position: 'Atacante' },
      { name: 'Giovanni Reyna', position: 'Atacante' },
      { name: 'Josh Sargent', position: 'Atacante' },
      { name: 'Jesús Ferreira', position: 'Atacante' },
    ],
  },
  {
    country: 'México',
    players: [
      { name: 'Guillermo Ochoa', position: 'Goleiro' },
      { name: 'Alfredo Talavera', position: 'Goleiro' },
      { name: 'César Montes', position: 'Defensor' },
      { name: 'Néstor Araujo', position: 'Defensor' },
      { name: 'Jesús Gallardo', position: 'Defensor' },
      { name: 'Jorge Sánchez', position: 'Defensor' },
      { name: 'Johan Vásquez', position: 'Defensor' },
      { name: 'Kevin Álvarez', position: 'Defensor' },
      { name: 'Héctor Herrera', position: 'Meio-campista' },
      { name: 'Edson Álvarez', position: 'Meio-campista' },
      { name: 'Andrés Guardado', position: 'Meio-campista' },
      { name: 'Carlos Rodríguez', position: 'Meio-campista' },
      { name: 'Luis Chávez', position: 'Meio-campista' },
      { name: 'Orbelin Pineda', position: 'Meio-campista' },
      { name: 'Hirving Lozano', position: 'Atacante' },
      { name: 'Raúl Jiménez', position: 'Atacante' },
      { name: 'Henry Martín', position: 'Atacante' },
      { name: 'Alexis Vega', position: 'Atacante' },
      { name: 'Uriel Antuna', position: 'Atacante' },
      { name: 'Roberto Alvarado', position: 'Atacante' },
    ],
  },
  {
    country: 'Uruguai',
    players: [
      { name: 'Sergio Rochet', position: 'Goleiro' },
      { name: 'Fernando Muslera', position: 'Goleiro' },
      { name: 'Diego Godín', position: 'Defensor' },
      { name: 'José María Giménez', position: 'Defensor' },
      { name: 'Ronald Araújo', position: 'Defensor' },
      { name: 'Sebastián Coates', position: 'Defensor' },
      { name: 'Martín Cáceres', position: 'Defensor' },
      { name: 'Mathías Olivera', position: 'Defensor' },
      { name: 'Federico Valverde', position: 'Meio-campista' },
      { name: 'Rodrigo Bentancur', position: 'Meio-campista' },
      { name: 'Matías Vecino', position: 'Meio-campista' },
      { name: 'Manuel Ugarte', position: 'Meio-campista' },
      { name: 'Giorgian De Arrascaeta', position: 'Meio-campista' },
      { name: 'Nicolás de la Cruz', position: 'Meio-campista' },
      { name: 'Luis Suárez', position: 'Atacante' },
      { name: 'Edinson Cavani', position: 'Atacante' },
      { name: 'Darwin Núñez', position: 'Atacante' },
      { name: 'Maxi Gómez', position: 'Atacante' },
      { name: 'Facundo Pellistri', position: 'Atacante' },
      { name: 'Facundo Torres', position: 'Atacante' },
    ],
  },
  {
    country: 'Senegal',
    players: [
      { name: 'Édouard Mendy', position: 'Goleiro' },
      { name: 'Alfred Gomis', position: 'Goleiro' },
      { name: 'Kalidou Koulibaly', position: 'Defensor' },
      { name: 'Abdou Diallo', position: 'Defensor' },
      { name: 'Pape Abou Cissé', position: 'Defensor' },
      { name: 'Youssouf Sabaly', position: 'Defensor' },
      { name: 'Formose Mendy', position: 'Defensor' },
      { name: 'Ismail Jakobs', position: 'Defensor' },
      { name: 'Idrissa Gueye', position: 'Meio-campista' },
      { name: 'Nampalys Mendy', position: 'Meio-campista' },
      { name: 'Cheikhou Kouyaté', position: 'Meio-campista' },
      { name: 'Pape Gueye', position: 'Meio-campista' },
      { name: 'Pathé Ciss', position: 'Meio-campista' },
      { name: 'Moustapha Name', position: 'Meio-campista' },
      { name: 'Sadio Mané', position: 'Atacante' },
      { name: 'Ismaïla Sarr', position: 'Atacante' },
      { name: 'Boulaye Dia', position: 'Atacante' },
      { name: 'Famara Diédhiou', position: 'Atacante' },
      { name: 'Krepin Diatta', position: 'Atacante' },
      { name: 'Iliman Ndiaye', position: 'Atacante' },
    ],
  },
  {
    country: 'Suíça',
    players: [
      { name: 'Yann Sommer', position: 'Goleiro' },
      { name: 'Gregor Kobel', position: 'Goleiro' },
      { name: 'Manuel Akanji', position: 'Defensor' },
      { name: 'Nico Elvedi', position: 'Defensor' },
      { name: 'Fabian Schär', position: 'Defensor' },
      { name: 'Ricardo Rodríguez', position: 'Defensor' },
      { name: 'Silvan Widmer', position: 'Defensor' },
      { name: 'Eray Cömert', position: 'Defensor' },
      { name: 'Granit Xhaka', position: 'Meio-campista' },
      { name: 'Remo Freuler', position: 'Meio-campista' },
      { name: 'Denis Zakaria', position: 'Meio-campista' },
      { name: 'Djibril Sow', position: 'Meio-campista' },
      { name: 'Michel Aebischer', position: 'Meio-campista' },
      { name: 'Fabian Rieder', position: 'Meio-campista' },
      { name: 'Xherdan Shaqiri', position: 'Atacante' },
      { name: 'Breel Embolo', position: 'Atacante' },
      { name: 'Haris Seferović', position: 'Atacante' },
      { name: 'Noah Okafor', position: 'Atacante' },
      { name: 'Ruben Vargas', position: 'Atacante' },
      { name: 'Christian Fassnacht', position: 'Atacante' },
    ],
  },
  {
    country: 'Dinamarca',
    players: [
      { name: 'Kasper Schmeichel', position: 'Goleiro' },
      { name: 'Frederik Rønnow', position: 'Goleiro' },
      { name: 'Simon Kjær', position: 'Defensor' },
      { name: 'Andreas Christensen', position: 'Defensor' },
      { name: 'Joachim Andersen', position: 'Defensor' },
      { name: 'Joakim Mæhle', position: 'Defensor' },
      { name: 'Rasmus Kristensen', position: 'Defensor' },
      { name: 'Victor Nelsson', position: 'Defensor' },
      { name: 'Christian Eriksen', position: 'Meio-campista' },
      { name: 'Pierre-Emile Højbjerg', position: 'Meio-campista' },
      { name: 'Thomas Delaney', position: 'Meio-campista' },
      { name: 'Mathias Jensen', position: 'Meio-campista' },
      { name: 'Mikkel Damsgaard', position: 'Meio-campista' },
      { name: 'Christian Nørgaard', position: 'Meio-campista' },
      { name: 'Martin Braithwaite', position: 'Atacante' },
      { name: 'Kasper Dolberg', position: 'Atacante' },
      { name: 'Andreas Skov Olsen', position: 'Atacante' },
      { name: 'Jesper Lindstrøm', position: 'Atacante' },
      { name: 'Jonas Wind', position: 'Atacante' },
      { name: 'Andreas Cornelius', position: 'Atacante' },
    ],
  },
  {
    country: 'Polônia',
    players: [
      { name: 'Wojciech Szczęsny', position: 'Goleiro' },
      { name: 'Łukasz Skorupski', position: 'Goleiro' },
      { name: 'Jan Bednarek', position: 'Defensor' },
      { name: 'Kamil Glik', position: 'Defensor' },
      { name: 'Matty Cash', position: 'Defensor' },
      { name: 'Bartosz Bereszyński', position: 'Defensor' },
      { name: 'Jakub Kiwior', position: 'Defensor' },
      { name: 'Robert Gumny', position: 'Defensor' },
      { name: 'Piotr Zieliński', position: 'Meio-campista' },
      { name: 'Grzegorz Krychowiak', position: 'Meio-campista' },
      { name: 'Kamil Grosicki', position: 'Meio-campista' },
      { name: 'Sebastian Szymański', position: 'Meio-campista' },
      { name: 'Damian Szymański', position: 'Meio-campista' },
      { name: 'Krystian Bielik', position: 'Meio-campista' },
      { name: 'Robert Lewandowski', position: 'Atacante' },
      { name: 'Arkadiusz Milik', position: 'Atacante' },
      { name: 'Karol Świderski', position: 'Atacante' },
      { name: 'Krzysztof Piątek', position: 'Atacante' },
      { name: 'Przemysław Frankowski', position: 'Atacante' },
      { name: 'Jakub Kamiński', position: 'Atacante' },
    ],
  },
];

/**
 * Executa o seed do banco de dados.
 * Limpa a tabela stickers e insere as 400 figurinhas.
 */
function seed(): void {
  console.log('🌱 Iniciando seed do banco de dados...\n');

  // Cria as tabelas se não existirem
  createTables();

  // Limpa as tabelas na ordem correta (por causa das foreign keys)
  console.log('🧹 Limpando tabelas existentes...');
  db.exec('DELETE FROM user_stickers');
  db.exec('DELETE FROM stickers');

  // Prepara a query de inserção
  const insertSticker = db.prepare(
    'INSERT INTO stickers (sticker_number, player_name, country, position) VALUES (?, ?, ?, ?)'
  );

  // Usa transação para melhor performance
  const insertAll = db.transaction(() => {
    let stickerNumber = 1;

    for (const team of teams) {
      console.log(`⚽ Inserindo seleção: ${team.country} (${team.players.length} jogadores)`);

      for (const player of team.players) {
        insertSticker.run(stickerNumber, player.name, team.country, player.position);
        stickerNumber++;
      }
    }

    return stickerNumber - 1;
  });

  const totalInserted = insertAll();

  console.log(`\n✅ Seed concluído com sucesso!`);
  console.log(`📊 Total de figurinhas inseridas: ${totalInserted}`);
  console.log(`🏆 Total de seleções: ${teams.length}`);
}

// Executa o seed
seed();

// Fecha a conexão com o banco
db.close();
